### ISSUE TITLE
Test macOS arm64 builds on real device

### ISSUE THREAD

**Issue by DrewCarlson** [DrewCarlson/ktpack#4]
Compiling and linking works as indented and reports the binaries are correct for an M1 device, but I only have an Intel based macbook to test with.  Because ktpack includes custom built static libraries, it's important that arm64 builds have some actual validation on device.

**Comment by DrewCarlson** [comment]
Much appreciated @vinsg!

I've pushed [a change](https://github.com/DrewCarlson/ktpack/commit/9dbb54d0dac85293c93f9b9c4d5d8a076ca25316) to bring the native library compilation process on M1/M2 inline with Intel machines, pull it down and let me know if `./gradlew clean packageReleaseMacos` works for you.  If it's successful, try running the CLI with `./ktpack/build/bin/macos/releaseExecutable/ktpack.kexe`

Please post any other questions or suggestions you may have for the project, the earlier the feedback the better ktpack will work for everyone :)  My goal is a stable alpha within the next month or so.

**Comment by vinsg** [comment]
Yes I can confirm it works fine now on macOS-arm64! thank you for the quick turnaround. 

I will be sure to ask questions ;)

**Comment by DrewCarlson** [comment]
Excellent, thanks!  I'll call this done for now and revisit if anything significant changes in the build setup.
